// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt-yaLX_vI65igNXSJEmLpha1cB8ZY4N4',
    appId: '1:109701841029:web:e99591ac481ebd82fbe9ec',
    messagingSenderId: '109701841029',
    projectId: 'mydic-53167',
    authDomain: 'mydic-53167.firebaseapp.com',
    storageBucket: 'mydic-53167.appspot.com',
    measurementId: 'G-6763SZ1NJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmPO2VIS-lxCESti8mP0mIl4aBl8UpprY',
    appId: '1:109701841029:android:0956670c64b8da50fbe9ec',
    messagingSenderId: '109701841029',
    projectId: 'mydic-53167',
    storageBucket: 'mydic-53167.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZbvkDWI5NgrZf7s12dVKf9af6fGxQb5g',
    appId: '1:109701841029:ios:60697c1845736732fbe9ec',
    messagingSenderId: '109701841029',
    projectId: 'mydic-53167',
    storageBucket: 'mydic-53167.appspot.com',
    iosClientId: '109701841029-29lg9ehcg00jj26ito7bcl8qsvs5is10.apps.googleusercontent.com',
    iosBundleId: 'com.bunooboi.mydic',
  );
}
